/* eslint-disable @typescript-eslint/no-unsafe-function-type, @typescript-eslint/no-explicit-any */
import { BoksProtocolError, BoksProtocolErrorId } from '../errors/BoksProtocolError';

/**
 * Metadata key used to store field definitions on the class constructor.
 */
const METADATA_KEY = Symbol('BoksPayloadMapper');

export type FieldType =
  | 'uint8'
  | 'uint16'
  | 'uint24'
  | 'uint32'
  | 'ascii_string'
  | 'mac_address'
  | 'hex_string'
  | 'pin_code'
  | 'config_key';

export interface FieldDefinition {
  propertyName: string;
  type: FieldType;
  offset: number;
  length?: number; // Required for strings/arrays
}

/**
 * Ensures the target class has a metadata array for field definitions.
 */
function getOrCreateMetadata(target: any): FieldDefinition[] {
  if (!target.constructor[METADATA_KEY]) {
    target.constructor[METADATA_KEY] = [];
  }
  return target.constructor[METADATA_KEY];
}

/**
 * Core Payload Mapper utility.
 * Compiles and executes JIT (Just-In-Time) parsing functions for extreme performance.
 */
export class PayloadMapper {
  // Cache of compiled parsing functions, keyed by Class Constructor
  private static compiledParsers = new Map<Function, Function>();
  // Cache of compiled serialization functions
  private static compiledSerializers = new Map<Function, Function>();
  private static compiledValidators = new Map<Function, Function>();

  /**
   * Pre-computed hex table for JIT compilers
   */
  private static readonly HEX_TABLE = Array.from({ length: 256 }, (_, i) =>
    i.toString(16).padStart(2, '0').toUpperCase()
  );

  /**
   * Security check: Validates that property names are safe identifiers
   * to prevent code injection into the JIT compiler via new Function().
   */
  private static assertSafePropertyName(name: string): void {
    // Prevent Prototype Pollution vectors (__proto__, constructor, prototype)
    const dangerousNames = ['__proto__', 'constructor', 'prototype'];
    if (!/^[a-zA-Z_$][0-9a-zA-Z_$]*$/.test(name) || dangerousNames.includes(name)) {
      throw new BoksProtocolError(
        BoksProtocolErrorId.INTERNAL_ERROR,
        `Unsafe property name mapped: ${name}`
      );
    }
  }

  /**
   * Security check: Validates bounds to prevent integer overflows
   * or unreasonable memory access definitions in the decorators.
   */
  private static assertSafeBounds(offset: number, size: number): void {
    if (
      offset < 0 ||
      size < 0 ||
      !Number.isSafeInteger(offset) ||
      !Number.isSafeInteger(size) ||
      offset + size > 1024
    ) {
      throw new BoksProtocolError(
        BoksProtocolErrorId.INTERNAL_ERROR,
        `Invalid mapping bounds: offset=${offset}, size=${size}`
      );
    }
  }

  /**
   * Compiles the JIT parsing function for a class.
   */
  private static compileParser(targetClass: any): Function {
    const fields: FieldDefinition[] =
      (targetClass[Symbol.metadata] &&
        targetClass[Symbol.metadata][Symbol.for('BoksPayloadMapperESMeta')]) ||
      targetClass[METADATA_KEY];
    if (!fields || fields.length === 0) {
      return (_payload: Uint8Array) => ({}); // No fields mapped
    }

    // Calculate maximum required payload size securely
    let minSize = 0;
    for (const field of fields) {
      this.assertSafePropertyName(field.propertyName);

      let size = 1; // Default min size
      if (field.type === 'uint16') {
        size = 2;
      } else if (field.type === 'uint24') {
        size = 3;
      } else if (field.type === 'uint32') {
        size = 4;
      } else if (field.type === 'mac_address') {
        size = 6;
      } else if (field.type === 'pin_code') {
        size = 6;
      } else if (field.type === 'config_key') {
        size = 8;
      } else if (field.type === 'ascii_string' || field.type === 'hex_string') {
        if (typeof field.length !== 'number') {
          throw new BoksProtocolError(
            BoksProtocolErrorId.INTERNAL_ERROR,
            `Length required for string type: ${field.type} on property ${field.propertyName}`
          );
        }
        size = field.length;
      }

      this.assertSafeBounds(field.offset, size);

      const endOffset = field.offset + size;
      if (endOffset > minSize) {
        minSize = endOffset;
      }
    }

    // Start building the Javascript function body as a string.
    // We explicitly throw a BoksProtocolError if the payload is too short,
    // which handles the "fuzzing malformed data" requirement.
    let fnBody = `
      // Auto-generated by PayloadMapper
      if (!(payload instanceof Uint8Array)) {
         throw new BoksProtocolError(BoksProtocolErrorId.MALFORMED_DATA, 'Payload must be a Uint8Array');
      }
      if (payload.length < ${minSize}) {
         throw new BoksProtocolError(
           BoksProtocolErrorId.MALFORMED_DATA,
           'Payload too short for mapped fields',
           { expectedAtLeast: ${minSize}, received: payload.length }
         );
      }
      const result = {};
    `;

    // Generate optimized extraction code for each field
    for (const field of fields) {
      const o = field.offset;
      const prop = field.propertyName;

      switch (field.type) {
        case 'uint8':
          fnBody += `result['${prop}'] = payload[${o}];\n`;
          break;
        case 'uint16':
          // Big Endian parsing
          fnBody += `result['${prop}'] = (payload[${o}] << 8) | payload[${o + 1}];\n`;
          break;
        case 'uint24':
          // Big Endian parsing
          fnBody += `result['${prop}'] = (payload[${o}] << 16) | (payload[${o + 1}] << 8) | payload[${o + 2}];\n`;
          break;
        case 'uint32':
          // Big Endian parsing (Note: >>> 0 ensures unsigned 32-bit result in JS)
          fnBody += `result['${prop}'] = ((payload[${o}] << 24) | (payload[${o + 1}] << 16) | (payload[${o + 2}] << 8) | payload[${o + 3}]) >>> 0;\n`;
          break;
        case 'ascii_string': {
          // Unrolled String.fromCharCode for fast ASCII extraction.
          const charArgs = [];
          for (let i = 0; i < field.length!; i++) {
            charArgs.push(`payload[${o + i}]`);
          }
          fnBody += `result['${prop}'] = String.fromCharCode(${charArgs.join(',')}).replace(/\\0/g, '');\n`;
          break;
        }
        case 'mac_address':
          // Reverse Little Endian to Big Endian (Standard Format: XX:XX:XX:XX:XX:XX)
          fnBody += `
            result['${prop}'] =
              HEX_TABLE[payload[${o + 5}]] + ':' +
              HEX_TABLE[payload[${o + 4}]] + ':' +
              HEX_TABLE[payload[${o + 3}]] + ':' +
              HEX_TABLE[payload[${o + 2}]] + ':' +
              HEX_TABLE[payload[${o + 1}]] + ':' +
              HEX_TABLE[payload[${o}]];
          `;
          break;
        case 'pin_code':
          // Inline validation for 6-char PIN: '0'-'9', 'A', 'B' (ASCII 48-57, 65-66)
          fnBody += `
             for(let i=0; i<6; i++) {
               const c = payload[${o} + i];
               if ((c < 48 || c > 57) && c !== 65 && c !== 66 && c !== 97 && c !== 98) {
                  throw new BoksProtocolError(BoksProtocolErrorId.INVALID_PIN_FORMAT, 'Invalid PIN character inline');
               }
             }
             result['${prop}'] = String.fromCharCode(payload[${o}], payload[${o + 1}], payload[${o + 2}], payload[${o + 3}], payload[${o + 4}], payload[${o + 5}]).toUpperCase();
           `;
          break;
        case 'config_key':
          // Inline validation for 8-char Config Key (Hex: 0-9, A-F)
          fnBody += `
             for(let i=0; i<8; i++) {
               const c = payload[${o} + i];
               // '0'-'9' (48-57), 'A'-'F' (65-70), 'a'-'f' (97-102)
               if ((c < 48 || c > 57) && (c < 65 || c > 70) && (c < 97 || c > 102)) {
                  throw new BoksProtocolError(BoksProtocolErrorId.INVALID_CONFIG_KEY, 'Invalid Config Key character inline');
               }
             }
             result['${prop}'] = String.fromCharCode(payload[${o}], payload[${o + 1}], payload[${o + 2}], payload[${o + 3}], payload[${o + 4}], payload[${o + 5}], payload[${o + 6}], payload[${o + 7}]).toUpperCase();
           `;
          break;
        case 'hex_string': {
          const hexArgs = [];
          for (let i = 0; i < field.length!; i++) {
            hexArgs.push(`HEX_TABLE[payload[${o + i}]]`);
          }
          fnBody += `result['${prop}'] = ${hexArgs.join(' + ')};\n`;
          break;
        }
      }
    }

    fnBody += `return result;\n`;

    // Compile the function, injecting external dependencies into the closure scope.
    return new Function('payload', 'BoksProtocolError', 'BoksProtocolErrorId', 'HEX_TABLE', fnBody);
  }

  /**
   * Compiles the JIT serialization function for a class.
   */

  /**
   * Compiles the JIT validation function for a class instance.
   * Used in constructors to validate manually provided properties.
   */
  private static compileValidator(targetClass: any): Function {
    const fields: FieldDefinition[] =
      (targetClass[Symbol.metadata] &&
        targetClass[Symbol.metadata][Symbol.for('BoksPayloadMapperESMeta')]) ||
      targetClass[METADATA_KEY];
    if (!fields || fields.length === 0) {
      return (_instance: any) => {};
    }

    let fnBody = `// Auto-generated by PayloadMapper.validate\n`;

    for (const field of fields) {
      this.assertSafePropertyName(field.propertyName);
      const prop = field.propertyName;
      const val = `instance['${prop}']`;

      if (field.type === 'pin_code') {
        fnBody += `
           if (typeof ${val} !== 'string' || ${val}.length !== 6) {
              throw new BoksProtocolError(BoksProtocolErrorId.INVALID_PIN_FORMAT, 'PIN must be exactly 6 characters');
           }
           for (let i = 0; i < 6; i++) {
              const c = ${val}.charCodeAt(i);
              if ((c < 48 || c > 57) && c !== 65 && c !== 66 && c !== 97 && c !== 98) {
                 throw new BoksProtocolError(BoksProtocolErrorId.INVALID_PIN_FORMAT, 'PIN must contain only 0-9, A, B');
              }
           }
         `;
      } else if (field.type === 'config_key') {
        fnBody += `
           if (typeof ${val} !== 'string' || ${val}.length !== 8) {
              throw new BoksProtocolError(BoksProtocolErrorId.INVALID_CONFIG_KEY, 'Config Key must be exactly 8 characters');
           }
           for (let i = 0; i < 8; i++) {
              const c = ${val}.charCodeAt(i);
              if ((c < 48 || c > 57) && (c < 65 || c > 70) && (c < 97 || c > 102)) {
                 throw new BoksProtocolError(BoksProtocolErrorId.INVALID_CONFIG_KEY, 'Config Key must contain only hex characters');
              }
           }
         `;
      }
      // Other types (uint8, etc.) could have type/bounds checks here if needed
    }

    return new Function('instance', 'BoksProtocolError', 'BoksProtocolErrorId', fnBody);
  }

  private static compileSerializer(targetClass: any): Function {
    const fields: FieldDefinition[] =
      (targetClass[Symbol.metadata] &&
        targetClass[Symbol.metadata][Symbol.for('BoksPayloadMapperESMeta')]) ||
      targetClass[METADATA_KEY];
    if (!fields || fields.length === 0) {
      return (_instance: any) => new Uint8Array(0); // No fields mapped
    }

    // Calculate maximum required payload size securely
    let size = 0;
    for (const field of fields) {
      this.assertSafePropertyName(field.propertyName);

      let fieldSize = 1;
      if (field.type === 'uint16') {
        fieldSize = 2;
      } else if (field.type === 'uint24') {
        fieldSize = 3;
      } else if (field.type === 'uint32') {
        fieldSize = 4;
      } else if (field.type === 'mac_address') {
        fieldSize = 6;
      } else if (field.type === 'pin_code') {
        fieldSize = 6;
      } else if (field.type === 'config_key') {
        fieldSize = 8;
      } else if (field.type === 'ascii_string' || field.type === 'hex_string') {
        fieldSize = field.length!;
      }

      this.assertSafeBounds(field.offset, fieldSize);

      const endOffset = field.offset + fieldSize;
      if (endOffset > size) {
        size = endOffset;
      }
    }

    let fnBody = `
      // Auto-generated by PayloadMapper
      if (!instance || typeof instance !== 'object') {
          throw new BoksProtocolError(BoksProtocolErrorId.INTERNAL_ERROR, 'Cannot serialize null or non-object instance');
      }
      const payload = new Uint8Array(${size});
    `;

    for (const field of fields) {
      const o = field.offset;
      const prop = field.propertyName;
      // We read the instance value. Missing values default to 0 for numbers, or empty string.
      const val = `(instance['${prop}'] || 0)`;
      const strVal = `(String(instance['${prop}'] || ''))`;

      switch (field.type) {
        case 'uint8':
          fnBody += `payload[${o}] = ${val};\n`;
          break;
        case 'uint16':
          fnBody += `payload[${o}] = (${val} >> 8) & 0xFF;\n`;
          fnBody += `payload[${o + 1}] = ${val} & 0xFF;\n`;
          break;
        case 'uint24':
          fnBody += `payload[${o}] = (${val} >> 16) & 0xFF;\n`;
          fnBody += `payload[${o + 1}] = (${val} >> 8) & 0xFF;\n`;
          fnBody += `payload[${o + 2}] = ${val} & 0xFF;\n`;
          break;
        case 'uint32':
          fnBody += `payload[${o}] = (${val} >>> 24) & 0xFF;\n`;
          fnBody += `payload[${o + 1}] = (${val} >>> 16) & 0xFF;\n`;
          fnBody += `payload[${o + 2}] = (${val} >>> 8) & 0xFF;\n`;
          fnBody += `payload[${o + 3}] = ${val} & 0xFF;\n`;
          break;
        case 'ascii_string':
          // Unrolled charCodeAt, pads with 0x00 if string is shorter than fixed length
          for (let i = 0; i < field.length!; i++) {
            fnBody += `payload[${o + i}] = ${strVal}.length > ${i} ? ${strVal}.charCodeAt(${i}) : 0;\n`;
          }
          break;
        case 'mac_address':
          // Reverse Mac formatting not yet supported for serialization in POC,
          // but we leave it empty to not break JIT. Downlinks rarely serialize MACs.
          break;
        case 'pin_code':
          for (let i = 0; i < 6; i++) {
            fnBody += `payload[${o + i}] = ${strVal}.length > ${i} ? ${strVal}.charCodeAt(${i}) : 48;\n`; // Default '0'
          }
          break;
        case 'config_key':
          for (let i = 0; i < 8; i++) {
            fnBody += `payload[${o + i}] = ${strVal}.length > ${i} ? ${strVal}.charCodeAt(${i}) : 48;\n`; // Default '0'
          }
          break;
        case 'hex_string':
          // Convert hex string back to bytes. Not fully implemented in POC serializer yet.
          break;
      }
    }

    fnBody += `return payload;\n`;
    return new Function('instance', 'BoksProtocolError', 'BoksProtocolErrorId', fnBody);
  }

  /**
   * Parses a payload directly into an object mapping using the JIT compiled function.
   *
   * @param targetClass The class constructor (e.g., OpenDoorPacket)
   * @param payload The raw buffer
   * @returns A mapped object containing the extracted properties
   */
  public static parse<T>(
    targetClass: { new (...args: any[]): T } | Function,
    payload: Uint8Array
  ): Partial<T> {
    let parser = this.compiledParsers.get(targetClass);
    if (!parser) {
      parser = this.compileParser(targetClass);
      this.compiledParsers.set(targetClass, parser);
    }
    const result = parser(payload, BoksProtocolError, BoksProtocolErrorId, this.HEX_TABLE);
    return result as Partial<T>;
  }

  /**
   * Serializes an instance into a Uint8Array payload using the JIT compiled function.
   */
  public static serialize(instance: any): Uint8Array {
    if (!instance || typeof instance !== 'object') {
      throw new BoksProtocolError(
        BoksProtocolErrorId.INTERNAL_ERROR,
        'Cannot serialize null or non-object instance'
      );
    }
    const targetClass = instance.constructor;
    let serializer = this.compiledSerializers.get(targetClass);
    if (!serializer) {
      serializer = this.compileSerializer(targetClass);
      this.compiledSerializers.set(targetClass, serializer);
    }
    return serializer(instance, BoksProtocolError, BoksProtocolErrorId);
  }

  /**
   * Defines a raw payload schema without decorators (useful for internal/dynamic mapping or tests).
   */

  /**
   * Validates an instance's properties based on its decorator schema.
   */
  public static validate(instance: any): void {
    const targetClass = instance.constructor;
    let validator = this.compiledValidators.get(targetClass);
    if (!validator) {
      validator = this.compileValidator(targetClass);
      this.compiledValidators.set(targetClass, validator);
    }
    validator(instance, BoksProtocolError, BoksProtocolErrorId);
  }

  public static defineSchema(targetClass: any, schema: FieldDefinition[]): void {
    targetClass[METADATA_KEY] = schema;
    // Clear any existing compiled functions for this class
    this.compiledParsers.delete(targetClass);
    this.compiledSerializers.delete(targetClass);
    this.compiledValidators.delete(targetClass);
  }
}

// --- Decorators ---

/**
 * Decorator to map an 8-bit unsigned integer field.
 */
export function PayloadUint8(offset: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'uint8', offset });
  };
}

/**
 * Decorator to map a 16-bit unsigned integer field (Big Endian).
 */
export function PayloadUint16(offset: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'uint16', offset });
  };
}

/**
 * Decorator to map a 24-bit unsigned integer field (Big Endian).
 */
export function PayloadUint24(offset: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'uint24', offset });
  };
}

/**
 * Decorator to map a 32-bit unsigned integer field (Big Endian).
 */
export function PayloadUint32(offset: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'uint32', offset });
  };
}

/**
 * Decorator to map a fixed-length ASCII string field.
 */
export function PayloadAsciiString(offset: number, length: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'ascii_string', offset, length });
  };
}

/**
 * Decorator to map a 6-byte MAC Address field.
 */
export function PayloadMacAddress(offset: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'mac_address', offset, length: 6 });
  };
}

/**
 * Decorator to map a fixed-length Hexadecimal string field.
 */
export function PayloadHexString(offset: number, length: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'hex_string', offset, length });
  };
}

/**
 * Decorator to map and validate a 6-character Boks PIN code field.
 * Intercepts the explicit setter.
 */
export function PayloadPinCode(offset: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'pin_code', offset, length: 6 });

    if (descriptor && descriptor.set) {
      const originalSet = descriptor.set;
      descriptor.set = function (val: any) {
        if (val === undefined || val === null) {
          originalSet.call(this, val);
          return;
        }
        const formatted = typeof val === 'string' ? val.toUpperCase() : String(val).toUpperCase();
        if (formatted.length !== 6) {
          throw new BoksProtocolError(
            BoksProtocolErrorId.INVALID_PIN_FORMAT,
            'PIN must be exactly 6 characters'
          );
        }
        for (let i = 0; i < 6; i++) {
          const c = formatted.charCodeAt(i);
          if ((c < 48 || c > 57) && c !== 65 && c !== 66 && c !== 97 && c !== 98) {
            throw new BoksProtocolError(
              BoksProtocolErrorId.INVALID_PIN_FORMAT,
              'PIN must contain only 0-9, A, B'
            );
          }
        }
        originalSet.call(this, formatted);
      };
    }
  };
}

/**
 * Decorator to map and validate an 8-character Boks Configuration Key field.
 * Intercepts the explicit setter.
 */
export function PayloadConfigKey(offset: number) {
  return function (target: any, propertyKey: string, descriptor?: PropertyDescriptor) {
    const meta = getOrCreateMetadata(target);
    meta.push({ propertyName: propertyKey, type: 'config_key', offset, length: 8 });

    if (descriptor && descriptor.set) {
      const originalSet = descriptor.set;
      descriptor.set = function (val: any) {
        if (val === undefined || val === null) {
          originalSet.call(this, val);
          return;
        }
        const formatted = typeof val === 'string' ? val.toUpperCase() : String(val).toUpperCase();
        if (formatted.length !== 8) {
          throw new BoksProtocolError(
            BoksProtocolErrorId.INVALID_CONFIG_KEY,
            'Config Key must be exactly 8 characters'
          );
        }
        for (let i = 0; i < 8; i++) {
          const c = formatted.charCodeAt(i);
          if ((c < 48 || c > 57) && (c < 65 || c > 70) && (c < 97 || c > 102)) {
            throw new BoksProtocolError(
              BoksProtocolErrorId.INVALID_CONFIG_KEY,
              'Config Key must contain only hex characters'
            );
          }
        }
        originalSet.call(this, formatted);
      };
    }
  };
}
